Name: Build EKOFLASH EXE

on:
  push:
    branches: [ "android-12.1", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          # لو استخدمت مكتبات خارجية مستقبلاً ضيفها هنا

      - name: Build EXE (No Console Mode)
        # تم إضافة --noconsole لإخفاء نافذة CMD الأساسية لبايثون
        run: pyinstaller --noconsole --onefile --name "EKOFLASH_PRO_v2.0" ekoflash.py

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: EKOFLASH_Windows_App
          path: dist/EKOFLASH_PRO_v2.0.exe
